import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import nodemailer from 'nodemailer';
import { createClient } from '@supabase/supabase-js';

dotenv.config();

const app = express();
const port = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.warn("WARNING: Supabase URL or Key is missing. Database operations will fail.");
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Ethereal Email Transporter
const createTestTransporter = async () => {
  if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
    return nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp-relay.brevo.com',
      port: process.env.SMTP_PORT || 587,
      secure: false, // Use STARTTLS
      auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS },
    });
  } else {
    let testAccount = await nodemailer.createTestAccount();
    return nodemailer.createTransport({
      host: "smtp.ethereal.email",
      port: 587,
      secure: false,
      auth: { user: testAccount.user, pass: testAccount.pass },
    });
  }
};

// -------------------------------------------------------------
// AUTH & REGISTRATION ROUTES
// -------------------------------------------------------------
app.post('/api/auth/register', async (req, res) => {
  try {
    const { 
      userName, userEmail, userPassword, 
      companyName, industry, phone, address, paymentDetails, auth_id 
    } = req.body;
    
    // Check if user already exists
    const { data: existingUser } = await supabase.from('users').select('*').eq('email', userEmail).single();
    if (existingUser) {
      return res.status(400).json({ success: false, message: 'Email already registered in Users database' });
    }

    // Step 1: Create Company Profile
    const { data: company, error: compError } = await supabase
      .from('companies')
      .insert([{ 
        name: companyName, industry, phone, address, 
        payment_proof: paymentDetails, 
        subscription_status: 'pending', is_approved: false 
      }])
      .select().single();

    if (compError) throw compError;

    // Step 2: Create User associated with the Company
    const { data: user, error: userError } = await supabase
      .from('users')
      .insert([{ 
        id: auth_id || undefined, // Store the secure Auth UUID generated by Supabase
        name: userName, email: userEmail, password: 'Managed by Supabase Auth', 
        is_admin: false, company_id: company.id 
      }])
      .select().single();

    if (userError) throw userError;

    // Optional: Pre-fill some default time slots for the company
    const defaultSlots = ['09:00 AM', '10:00 AM', '11:00 AM', '01:00 PM', '02:00 PM', '03:00 PM', '04:00 PM'];
    const slotPayloads = defaultSlots.map(t => ({ company_id: company.id, time_slot: t }));
    await supabase.from('company_time_slots').insert(slotPayloads);

    res.status(200).json({ success: true, user, company });
  } catch (error) {
    console.error('Registration Error:', error);
    res.status(500).json({ success: false, message: 'Failed to complete registration' });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password, auth_id } = req.body;
    
    // Authenticate through the unified "users" table
    // If the frontend already verified the password via Supabase Auth, we look up by auth_id or email
    let query = supabase.from('users').select('*, companies(*)').eq('email', email);
    
    // Backwards compatibility for accounts created before Supabase Auth was added
    if (!auth_id) {
       query = query.eq('password', password); 
    }

    const { data: user, error } = await query.single();

    if (error || !user) {
      return res.status(400).json({ success: false, message: 'Invalid email or password.' });
    }

    if (user.is_admin) {
      return res.status(200).json({ success: true, role: 'admin', user });
    }
    
    res.status(200).json({ success: true, role: 'company', user: { ...user, company: user.companies } });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ success: false, message: 'Login execution failed' });
  }
});


// -------------------------------------------------------------
// CUSTOMER BOOKING ROUTES
// -------------------------------------------------------------
app.get('/api/companies', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('companies')
      .select('id, name, industry, description, address, phone')
      .eq('subscription_status', 'active');
      
    if (error) throw error;
    res.status(200).json({ success: true, companies: data });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch companies' });
  }
});

app.get('/api/meetings/slots', async (req, res) => {
  try {
    const { company_id, date } = req.query;

    // First check if the date is explicitly blocked by the company
    const { data: blockedData, error: blockErr } = await supabase
      .from('company_blocked_dates')
      .select('blocked_date')
      .eq('company_id', company_id)
      .eq('blocked_date', date)
      .single();

    if (blockErr && blockErr.code !== 'PGRST116') { // PGRST116 = No rows found
       throw blockErr;
    }

    if (blockedData) {
       // The date is blocked, return immediately
       return res.status(200).json({ success: true, isBlocked: true, availableSlots: [] });
    }
    
    // Continue with getting available slots for an unblocked date
    const { data: offeredSlots, error: offErr } = await supabase
      .from('company_time_slots')
      .select('time_slot')
      .eq('company_id', company_id);
    if (offErr) throw offErr;
    const allCompanySlots = offeredSlots.map(s => s.time_slot);

    // Then, query which of those slots are already taken perfectly for that specific date
    const { data: taken, error } = await supabase
      .from('meetings')
      .select('time_slot')
      .eq('company_id', company_id)
      .eq('date', date)
      .in('status', ['pending', 'confirmed']);
      
    if (error) throw error;
    const bookedSlotsMap = taken.map(m => m.time_slot);
    
    // The available slots is the array of natively offered slots MINUS the booked ones
    const availableSlots = allCompanySlots.filter(slot => !bookedSlotsMap.includes(slot));
    
    res.status(200).json({ success: true, isBlocked: false, availableSlots });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch time slots logic' });
  }
});

app.post('/api/meetings/book', async (req, res) => {
  try {
    const { company_id, customer_details, date, time_slot } = req.body;
    
    const { data, error } = await supabase
      .from('meetings')
      .insert([{ company_id, customer_details, date, time_slot, status: 'pending' }]);
      
    if (error) throw error;
    res.status(200).json({ success: true, message: 'Meeting requested successfully.' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to request meeting.' });
  }
});


// -------------------------------------------------------------
// CALENDAR & COMPANY TIME SLOT MANAGEMENT ROUTES
// -------------------------------------------------------------
app.get('/api/company/:companyId/availability', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('company_time_slots')
      .select('*')
      .eq('company_id', req.params.companyId)
      .order('time_slot', { ascending: true });
      
    if (error) throw error;
    res.status(200).json({ success: true, timeSlots: data });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch calendar slots' });
  }
});

app.post('/api/company/:companyId/availability', async (req, res) => {
  try {
    const { time_slot } = req.body;
    
    // Validate formatting (optional but safe)
    if (!time_slot) throw new Error("Time slot required");
    
    const { data, error } = await supabase
      .from('company_time_slots')
      .insert([{ company_id: req.params.companyId, time_slot }])
      .select().single();
      
    if (error) {
       if (error.code === '23505') { // Postgres distinctive UNIQUE violation code
         return res.status(400).json({ success: false, message: 'Time slot already exists!' });
       }
       throw error;
    }
    res.status(200).json({ success: true, slot: data });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Failed to add time slot' });
  }
});

app.delete('/api/company/availability/:slotId', async (req, res) => {
  try {
    const { error } = await supabase
      .from('company_time_slots')
      .delete()
      .eq('id', req.params.slotId);
      
    if (error) throw error;
    res.status(200).json({ success: true, message: 'Time slot deleted' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to delete slot' });
  }
});

app.get('/api/company/:companyId/blocked-dates', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('company_blocked_dates')
      .select('*')
      .eq('company_id', req.params.companyId);
      
    if (error) throw error;
    res.status(200).json({ success: true, blockedDates: data });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch blocked dates' });
  }
});

app.post('/api/company/:companyId/block-date', async (req, res) => {
  try {
    const { blocked_date } = req.body;
    if (!blocked_date) throw new Error("Blocked date required");
    
    const { data, error } = await supabase
      .from('company_blocked_dates')
      .insert([{ company_id: req.params.companyId, blocked_date }])
      .select().single();
      
    if (error) {
       if (error.code === '23505') { 
         return res.status(400).json({ success: false, message: 'Date already blocked!' });
       }
       throw error;
    }
    res.status(200).json({ success: true, blockedDate: data });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Failed to block date' });
  }
});

app.delete('/api/company/blocked-dates/:dateId', async (req, res) => {
  try {
    const { error } = await supabase
      .from('company_blocked_dates')
      .delete()
      .eq('id', req.params.dateId);
      
    if (error) throw error;
    res.status(200).json({ success: true, message: 'Blocked date removed' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to remove blocked date' });
  }
});


// -------------------------------------------------------------
// CLIENT (COMPANY) ADMIN ROUTES
// -------------------------------------------------------------
app.get('/api/company/:companyId/dashboard', async (req, res) => {
  try {
    const { companyId } = req.params;
    const { data: meetings, error: mError } = await supabase
      .from('meetings')
      .select('*')
      .eq('company_id', companyId)
      .order('date', { ascending: true });
      
    if (mError) throw mError;
    res.status(200).json({ success: true, meetings });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch dashboard data' });
  }
});

app.post('/api/meetings/confirm', async (req, res) => {
  try {
    const { meetingId, customerName, customerEmail, companyName, date, time } = req.body;

    const { error } = await supabase
      .from('meetings')
      .update({ status: 'confirmed' })
      .eq('id', meetingId);
      
    if (error) throw error;

    const mockGoogleMeetLink = `https://meet.google.com/mock-${Math.random().toString(36).substr(2, 9)}`;
    const transporter = await createTestTransporter();
    
    const htmlTemplate = `
      <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <h2 style="color: #4F46E5;">Meeting Confirmed!</h2>
        <p>Hi ${customerName},</p>
        <p>Your meeting with <strong>${companyName}</strong> has been officially confirmed.</p>
        <div style="background-color: #F8FAFC; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #E2E8F0;">
          <p style="margin: 0 0 10px 0;"><strong>Date:</strong> ${date}</p>
          <p style="margin: 0 0 10px 0;"><strong>Time:</strong> ${time}</p>
          <p style="margin: 0;"><strong>Join Link:</strong> <a href="${mockGoogleMeetLink}" style="color: #4F46E5;">${mockGoogleMeetLink}</a></p>
        </div>
      </div>
    `;

    let info = await transporter.sendMail({
      from: '"Schedulr" <masteradmin.schedulr@gmail.com>',
      to: customerEmail || 'test@example.com',
      subject: `Meeting Confirmed: ${companyName}`,
      html: htmlTemplate,
    });

    res.status(200).json({ 
      success: true, 
      message: 'Meeting confirmed. Email sent.',
      emailPreviewUrl: nodemailer.getTestMessageUrl(info)
    });

  } catch (error) {
    console.error('Email/Confirm Error:', error);
    res.status(500).json({ success: false, message: error.message || 'Failed to confirm meeting' });
  }
});

app.post('/api/meetings/decline', async (req, res) => {
  try {
    const { meetingId } = req.body;
    const { error } = await supabase.from('meetings').update({ status: 'declined' }).eq('id', meetingId);
    if (error) throw error;
    res.status(200).json({ success: true, message: 'Meeting declined.' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to decline meeting' });
  }
});


// -------------------------------------------------------------
// MASTER ADMIN ROUTES
// -------------------------------------------------------------
app.get('/api/admin/dashboard', async (req, res) => {
  try {
    // We fetch users whose is_admin is false and join with companies
    // Thus giving us access to company info AND the registered user's email
    const { data: usersInfo, error: cError } = await supabase
      .from('users')
      .select('*, companies(*)')
      .eq('is_admin', false);
      
    if (cError) throw cError;

    // Formatting for the frontend master table logic
    const companiesFormatted = usersInfo.map(u => ({
      id: u.companies.id, // we identify primarily by company_id for the UI grid toggles
      name: u.companies.name,
      email: u.email, // Use the user's email login here
      industry: u.companies.industry,
      payment_proof: u.companies.payment_proof,
      subscription_status: u.companies.subscription_status,
      created_at: u.companies.created_at
    }));

    const { data: meetings, error: mError } = await supabase
      .from('meetings')
      .select('*, companies(name)')
      .order('created_at', { ascending: false });
      
    if (mError) throw mError;
    
    const formattedMeetings = meetings.map(m => ({ ...m, companyName: m.companies?.name || 'Unknown' }));

    res.status(200).json({ success: true, companies: companiesFormatted, meetings: formattedMeetings });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch admin data' });
  }
});

app.put('/api/admin/company/:id', async (req, res) => {
  try {
    const { action, status } = req.body; 
    let updatePayload = {};
    if (action === 'approve') updatePayload = { subscription_status: 'active', is_approved: true };
    else if (action === 'toggle') updatePayload = { subscription_status: status };
    else if (action === 'reject') {
      await supabase.from('companies').delete().eq('id', req.params.id); // Cascade deletes users
      return res.status(200).json({ success: true, message: 'Company rejected' });
    }

    const { error } = await supabase.from('companies').update(updatePayload).eq('id', req.params.id);
    if (error) throw error;

    res.status(200).json({ success: true, message: 'Company updated' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to update company' });
  }
});

app.listen(port, () => {
  console.log(`Server is running on port: ${port}`);
});
